### ISSUE TITLE
Duplicate SSH config

### ISSUE THREAD

**Issue by mtnbikenc** [csc/kragle#12]
SSH configuration is performed in both the kickstart files and in the `base` Ansible role.  Only one place should be chosen, and the config differences in each place should be consolidated.

Kickstart:
https://github.com/csc/kragle/blob/67dd45df7e266d169bb5007d0dec5be235baeb86/kickstart-files/ks-isolinux.cfg#L69-L75

Base Role:
https://github.com/csc/kragle/blob/67dd45df7e266d169bb5007d0dec5be235baeb86/ansible/roles/base/tasks/main.yml#L37-L41

**Comment by mtnbikenc** [comment]
Ah, looks like the ssh config is removed later in the kickstart after running git clone for kragle.

**Comment by tjmcs** [comment]
Yeah, was about to comment on that...the kick-start configuration is just to ensure that the install completes without asking for approval for a SSH connection during the installation process
